### PR TITLE
API 2.0

### PR DESCRIPTION
**Pull request by mistzzt**

### CODE REVIEW

**Comment by hakusaro** [comment]
@mistzzt if you'd be up for it, we'd much prefer if you took over development or maintenance of this plugin and uploaded it on the forums

**Comment by mistzzt** [comment]
okay, i am able to do that.

**Comment by mistzzt** [comment]
so what should i do now?

**Comment by hakusaro** [comment]
@mistzzt I mean you can keep the PR but you could just release the fork you have on RM?

**Comment by AxisKriel** [comment]
@mistzzt 
Just like Lucas suggested, you should visit https://tshock.co/xf/index.php?resources/ and hit Add Resource. You can copy most descriptions from the original resource page to make your job easier, but the source URL should point to your fork on GitHub instead of here. After you've done that, we will approve your plugin and this PR may be closed as there will be no reason to keep it.

(you might have received a notification saying ownership of the original WorldEdit has been transfered to you, and that would be my fault; I originally thought that would make things easier but as it turns out, it is actually far more complicated and less clear than adding a new resource)

**Comment by mistzzt** [comment]
okay, i understand. I will release my fork on PM asap.

**Pull request closed without merging**
