### PR TITLE
Make //shift command actually work (bad array index)

### PR DESCRIPTION
**Pull request by epylar**

### CODE REVIEW

**Comment by hakusaro** [comment]
Appreciate the thought. Can you release and maintain a fork of WorldEdit on the forums?

**Comment by hakusaro** [comment]
[We haven't been able to maintain it]

**Comment by epylar** [comment]
Trouble maintaining it due to lack of resources/time, or specific technical problems?  (I compiled this with my patch and tried it out on latest TShock/latest Terraria and the command seemed to work fine after the fix.)

**Comment by epylar** [comment]
Oh, I see, you are the official maintainers/authors of TShock.  Sure, I can at least do a release and see where it goes.  I see there's an existing thread on https://tshock.co/xf/index.php?threads/worldedit.1608/ -- would there be a new thread?

**Comment by hakusaro** [comment]
> Trouble maintaining it due to lack of resources/time, or specific technical problems?

MarioE, the person who was developing this plugin, and is also on the TShock team, was going to do a whole rewrite of everything. We postponed releasing anything related to it figuring he would pick the project back up, but he didn't. The last person who sent patches we urged to fork and they never did anything.

> Oh, I see, you are the official maintainers/authors of TShock. Sure, I can at least do a release and see where it goes. I see there's an existing thread on https://tshock.co/xf/index.php?threads/worldedit.1608/ -- would there be a new thread?

It's up to you. You would submit the plugin in resource manager, and release it on your own schedule. If you want, we could merge the old WorldEdit thread with your thread, or you could just start fresh.

**Comment by AxisKriel** [comment]
I currently own the WorldEdit resource page @ tshock.co but my release contains mostly compatibility changes and is not perfect, as I don't have the time to fully commit to it. I can delete the resource if you wish, to allow you to pick it up.

**Comment by hakusaro** [comment]
@enerdy sorry for stepping on your shoes. Maybe you both could work to a solution on this then?

**Comment by epylar** [comment]
@enerdy I'm not sure I have a huge amount of time, but let's work on getting a new release out with this patch in it to start with.   Are you saying you'd like to hand ownership to me?  Could you walk me through the process I'd need to use to release a new version?

**Comment by AxisKriel** [comment]
Heck, even if we never reached an agreement (mostly my fault for not answering back), this should've never been left unmerged for this long lol. A fix is a fix.

**Pull request merged**
